In [1]:
import numpy as np
import pandas as pd
import os.path as op
from sklearn.feature_selection import SelectKBest, chi2
import pickle
from scipy.fft import fft, fftfreq
from tqdm import tqdm

In [2]:
def load_obj(name, path):
    with open(op.join(path, name), 'rb') as f:
        return pickle.load(f)

In [3]:
results_df = pd.DataFrame(load_obj("modelling_agregated_feature.pkl","/sps/crnl/ademasson/data/features_extraction"))
results_df

agr_test_cv_0  agr_pred_cv_0  agr_test_cv_1  agr_pred_cv_1  \
0              False              0          False              0   
1              False              0          False              0   
2              False              0          False              0   
3              False              0          False              0   
4              False              0          False              0   
...              ...            ...            ...            ...   
24907          False              0          False              0   
24908          False              0          False              0   
24909          False              0          False              0   
24910          False              0          False              0   
24911          False              0          False              0   

       agr_test_cv_2  agr_pred_cv_2  agr_test_cv_3  agr_pred_cv_3  \
0              False              0          False              0   
1              False              0          False              0   
2              False              0          False              0   
3              False              0          False              0   
4              False              0          False              0   
...              ...            ...            ...            ...   
24907          False              0          False              0   
24908          False              0          False              0   
24909          False              0          False              0   
24910          False              0          False              0   
24911          False              0          False              0   

       agr_test_cv_4  agr_pred_cv_4  
0              False              0  
1              False              0  
2              False              0  
3              False              0  
4              False              0  
...              ...            ...  
24907          False              0  
24908          False              0  
24909          False              0  
24910          False              0  
24911          False              0  

[24912 rows x 10 columns]

In [4]:
test_columns = [col for col in results_df.columns.tolist() if col.startswith('agr_test_')]
test_columns

['agr_test_cv_0',
 'agr_test_cv_1',
 'agr_test_cv_2',
 'agr_test_cv_3',
 'agr_test_cv_4']

In [5]:
pred_columns = [col for col in results_df.columns.tolist() if col.startswith('agr_pred_')]
pred_columns

['agr_pred_cv_0',
 'agr_pred_cv_1',
 'agr_pred_cv_2',
 'agr_pred_cv_3',
 'agr_pred_cv_4']

In [6]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [7]:
ncv = 1
for test, pred in zip(test_columns, pred_columns):
    print(f"CV {ncv}")
    print(confusion_matrix(results_df[test], results_df[pred]))
    print(classification_report(results_df[test], results_df[pred]))
    ncv +=1

CV 1
[[24148     6]
 [  758     0]]
              precision    recall  f1-score   support

       False       0.97      1.00      0.98     24154
        True       0.00      0.00      0.00       758

    accuracy                           0.97     24912
   macro avg       0.48      0.50      0.49     24912
weighted avg       0.94      0.97      0.95     24912

CV 2
[[24364     6]
 [  542     0]]
              precision    recall  f1-score   support

       False       0.98      1.00      0.99     24370
        True       0.00      0.00      0.00       542

    accuracy                           0.98     24912
   macro avg       0.49      0.50      0.49     24912
weighted avg       0.96      0.98      0.97     24912

CV 3
[[24312     0]
 [  600     0]]
              precision    recall  f1-score   support

       False       0.98      1.00      0.99     24312
        True       0.00      0.00      0.00       600

    accuracy                           0.98     24912
   macro avg       0

/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
