In [2]:
import numpy as np
import pandas as pd
import os.path as op
from sklearn.feature_selection import SelectKBest, chi2
import pickle
from scipy.fft import fft, fftfreq
from tqdm import tqdm

In [3]:
def load_obj(name, path):
    with open(op.join(path, name), 'rb') as f:
        return pickle.load(f)

In [4]:
results_df = pd.DataFrame(load_obj("modelling_8_feature.pkl","/sps/crnl/ademasson/data/features_extraction"))
results_df

f_8_test_cv_0  f_8_pred_cv_0  f_8_test_cv_1  f_8_pred_cv_1  \
0              False              0          False              0   
1              False              0          False              0   
2              False              0          False              0   
3              False              0          False              0   
4              False              0          False              0   
...              ...            ...            ...            ...   
24907          False              0          False              0   
24908          False              0          False              0   
24909          False              0          False              0   
24910          False              0          False              0   
24911          False              0          False              0   

       f_8_test_cv_2  f_8_pred_cv_2  f_8_test_cv_3  f_8_pred_cv_3  \
0              False              0          False              0   
1              False              0          False              0   
2              False              0          False              0   
3              False              0          False              0   
4              False              0          False              0   
...              ...            ...            ...            ...   
24907          False              0          False              0   
24908          False              0          False              0   
24909          False              0          False              0   
24910          False              0          False              0   
24911          False              0          False              0   

       f_8_test_cv_4  f_8_pred_cv_4  
0              False              0  
1              False              0  
2              False              0  
3              False              0  
4              False              0  
...              ...            ...  
24907          False              0  
24908          False              0  
24909          False              0  
24910          False              0  
24911          False              0  

[24912 rows x 10 columns]

In [16]:
y= {}
for i in range(1,6):
    y[f'f_{str(i)}'] = {f'cv_{str(j+1)}': {"test": results_df[f'f_{str(i)}_test_cv_{str(j)}'], "pred": results_df[f'f_{str(i)}_pred_cv_{str(j)}']} for j in range(0,5)}

In [28]:
y[f'f_{str(8)}'] = {f'cv_{str(j+1)}': {"test": results_df[f'f_{str(8)}_test_cv_{str(j)}'], "pred": results_df[f'f_{str(8)}_pred_cv_{str(j)}']} for j in range(0,5)}

In [30]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [33]:
for f, cv in y.items():
    print(f"-----{f[-1]} features-----")
    for ncv, res in cv.items():
        print(f"CV {ncv[-1]}")
        print(confusion_matrix(res['test'], res['pred']))
        print(classification_report(res['test'], res['pred']))

-----1 features-----
CV 1
[[23977   177]
 [  750     8]]
              precision    recall  f1-score   support

       False       0.97      0.99      0.98     24154
        True       0.04      0.01      0.02       758

    accuracy                           0.96     24912
   macro avg       0.51      0.50      0.50     24912
weighted avg       0.94      0.96      0.95     24912

CV 2
[[24235   135]
 [  540     2]]
              precision    recall  f1-score   support

       False       0.98      0.99      0.99     24370
        True       0.01      0.00      0.01       542

    accuracy                           0.97     24912
   macro avg       0.50      0.50      0.50     24912
weighted avg       0.96      0.97      0.96     24912

CV 3
[[24157   155]
 [  590    10]]
              precision    recall  f1-score   support

       False       0.98      0.99      0.98     24312
        True       0.06      0.02      0.03       600

    accuracy                           0.97     24912

/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

       False       0.94      1.00      0.97     23514
        True       0.37      0.01      0.01      1398

    accuracy                           0.94     24912
   macro avg       0.66      0.50      0.49     24912
weighted avg       0.91      0.94      0.92     24912

-----2 features-----
CV 1
[[24154     0]
 [  758     0]]
              precision    recall  f1-score   support

       False       0.97      1.00      0.98     24154
        True       0.00      0.00      0.00       758

    accuracy                           0.97     24912
   macro avg       0.48      0.50      0.49     24912
weighted avg       0.94      0.97      0.95     24912

CV 2
[[24370     0]
 [  542     0]]
              precision    recall  f1-score   support

       False       0.98      1.00      0.99     24370
        True       0.00      0.00      0.00       542

    accuracy                           0.98     24912
   macro avg       0.49      0.50  

/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

       False       0.94      1.00      0.97     23514
        True       0.00      0.00      0.00      1398

    accuracy                           0.94     24912
   macro avg       0.47      0.50      0.49     24912
weighted avg       0.89      0.94      0.92     24912

-----3 features-----
CV 1
[[23859   295]
 [  737    21]]
              precision    recall  f1-score   support

       False       0.97      0.99      0.98     24154
        True       0.07      0.03      0.04       758

    accuracy                           0.96     24912
   macro avg       0.52      0.51      0.51     24912
weighted avg       0.94      0.96      0.95     24912

CV 2
[[24082   288]
 [  539     3]]
              precision    recall  f1-score   support

       False       0.98      0.99      0.98     24370
        True       0.01      0.01      0.01       542

    accuracy                           0.97     24912
   macro avg       0.49      0.50  

/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       False       0.94      1.00      0.97     23514
        True       0.36      0.02      0.03      1398

    accuracy                           0.94     24912
   macro avg       0.65      0.51      0.50     24912
weighted avg       0.91      0.94      0.92     24912

-----5 features-----
CV 1
[[23625   529]
 [  723    35]]
              precision    recall  f1-score   support

       False       0.97      0.98      0.97     24154
        True       0.06      0.05      0.05       758

    accuracy                           0.95     24912
   macro avg       0.52      0.51      0.51     24912
weighted avg       0.94      0.95      0.95     24912

CV 2
[[23670   700]
 [  523    19]]
              precision    recall  f1-score   support

       False       0.98      0.97      0.97     24370
        True       0.03      0.04      0.03       542

    accuracy                           0.95     24912
   macro avg       0.50      0.50  